import React from 'react';
import { Shield, Lock, Eye, FileText, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

const Privacy = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <Link to="/home" className="inline-flex items-center text-neon-green hover:text-white transition-colors mb-8 group uppercase tracking-widest font-black italic text-xs">
        <ArrowLeft className="w-4 h-4 mr-2 transform group-hover:-translate-x-1 transition-transform" />
        // Return to Operations
      </Link>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-black/60 border border-white/5 rounded-3xl p-8 md:p-12 backdrop-blur-xl shadow-[0_0_50px_rgba(0,255,255,0.05)] relative overflow-hidden"
      >
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-neon-green via-transparent to-neon-blue opacity-50" />
        
        <div className="flex items-center space-x-6 mb-12">
          <div className="w-16 h-16 bg-black/40 rounded-2xl flex items-center justify-center border border-neon-green/30 shadow-[0_0_15px_rgba(0,255,255,0.2)]">
            <Shield className="w-8 h-8 text-neon-green" />
          </div>
          <div>
            <h1 className="text-4xl font-display font-black text-white italic tracking-tighter uppercase">Privacy // Protocol</h1>
            <p className="text-neon-blue text-xs font-bold tracking-[0.2em] mt-2">LAST SYNC: APRIL 16, 2026</p>
          </div>
        </div>

        <div className="prose prose-invert prose-slate max-w-none space-y-10">
          <section>
            <h2 className="text-xl font-black text-white flex items-center mb-4 italic uppercase tracking-widest">
              <Eye className="w-5 h-5 mr-3 text-neon-green" /> 01. Neural Overview
            </h2>
            <p className="text-gray-400 leading-relaxed font-medium">
              At AgriBot Core, we maintain lethal precision in data protection. This protocol defines how we process, encrypt, and safeguard your agricultural telemetry within our neural networks.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black text-white flex items-center mb-4 italic uppercase tracking-widest">
              <FileText className="w-5 h-5 mr-3 text-neon-green" /> 02. Data Sovereignty
            </h2>
            <p className="text-gray-400 leading-relaxed font-medium">
              <span className="text-white font-bold">The Architect Owns the Data.</span> Any telemetry generated by your operations remains your absolute property. AgriBot Core is merely the processing interface.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black text-white flex items-center mb-4 italic uppercase tracking-widest">
              <Lock className="w-5 h-5 mr-3 text-neon-green" /> 03. Telemetry Collection
            </h2>
            <ul className="list-none pl-4 text-gray-400 space-y-4 font-medium border-l border-white/10">
              <li className="flex items-start">
                <span className="text-neon-green mr-3">//</span>
                <span><strong className="text-white">Uplink Signals:</strong> Secure identifiers and farm coordinates.</span>
              </li>
              <li className="flex items-start">
                <span className="text-neon-green mr-3">//</span>
                <span><strong className="text-white">Bio-Scans:</strong> High-resolution crop imagery and pathogen metadata.</span>
              </li>
              <li className="flex items-start">
                <span className="text-neon-green mr-3">//</span>
                <span><strong className="text-white">Core Metrics:</strong> Diagnostic logs and predictive analysis history.</span>
              </li>
            </ul>
          </section>

          <section className="bg-neon-blue/5 p-8 rounded-2xl border border-neon-blue/20">
            <h3 className="text-lg font-black text-white mb-3 italic tracking-widest uppercase">Data Extraction</h3>
            <p className="text-gray-400 text-sm leading-relaxed font-medium">
              You retain the right to terminate your uplink and purge all associated data nodes. Purge requests are executed across all redundant servers within 72 cycles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black text-white mb-6 italic uppercase tracking-widest">04. Encryption Support</h2>
            <p className="text-gray-400 leading-relaxed font-medium">
              Direct connection to the Data Protection Architect:
              <br />
              <Link to="https://mail.google.com/mail/?view=cm&fs=1&to=iamhriturajsaha@gmail.com" target="_blank" className="text-neon-green hover:text-neon-blue transition-colors font-bold underline decoration-2 underline-offset-4">iamhriturajsaha@gmail.com</Link>
            </p>
          </section>
        </div>
      </motion.div>
    </div>
  );
};

export default Privacy;
