# -*- coding: utf-8 -*-
"""Crop Yield Prediction Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmXbbB1szKbCHf9XrpleUFxzd6cq_-Ev
"""

# Crop Yield Prediction Model

# Install Libraries
!pip install pandas numpy scikit-learn xgboost joblib

# Import Libraries
import pandas as pd
import numpy as np
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor
import joblib

# Upload Dataset
uploaded = files.upload()

# Load Dataset
df = pd.read_csv("Crop Production.csv")
df.head()

# Feature Engineering
# Create yield
df = df[df["Area"] > 0]
df["Yield"] = df["Production"] / df["Area"]

# Remove extreme outliers
df = df[df["Yield"] < df["Yield"].quantile(0.99)]

# Log transform target
df["Yield_log"] = np.log1p(df["Yield"])

# Drop District Column
df = df.drop("District_Name", axis=1)

# Encode Categorical Variables
df = pd.get_dummies(
    df,
    columns=["State_Name", "Season", "Crop"],
    drop_first=True
)

# Split Dataset
X = df.drop(["Production", "Yield", "Yield_log"], axis=1)
y = df["Yield_log"]
feature_columns = X.columns

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Model
model = XGBRegressor(
    n_estimators=400,
    max_depth=10,
    learning_rate=0.05,
    random_state=42
)
model.fit(X_train, y_train)

# Evaluate
pred_log = model.predict(X_test)
pred = np.expm1(pred_log)
y_true = np.expm1(y_test)
rmse = np.sqrt(mean_squared_error(y_true, pred))
r2 = r2_score(y_true, pred)
print("RMSE:", rmse)
print("R2 Score:", r2)

# Save Model and Download
joblib.dump(model, "yield_prediction_model.pkl")
joblib.dump(feature_columns, "yield_feature_columns.pkl")
files.download("yield_prediction_model.pkl")
files.download("yield_feature_columns.pkl")