import React from 'react';
import { Shield, Lock, Eye, FileText, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

const Privacy = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <Link to="/home" className="inline-flex items-center text-agri-lightGreen hover:text-white transition-colors mb-8 group">
        <ArrowLeft className="w-4 h-4 mr-2 transform group-hover:-translate-x-1 transition-transform" />
        Back to Home
      </Link>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-slate-900/40 border border-slate-800 rounded-3xl p-8 md:p-12 backdrop-blur-xl shadow-2xl"
      >
        <div className="flex items-center space-x-4 mb-8">
          <div className="w-12 h-12 bg-agri-green/20 rounded-2xl flex items-center justify-center border border-agri-green/30">
            <Shield className="w-6 h-6 text-agri-lightGreen" />
          </div>
          <div>
            <h1 className="text-3xl font-display font-bold text-white">Privacy Policy</h1>
            <p className="text-slate-400 text-sm">Last updated: April 16, 2026</p>
          </div>
        </div>

        <div className="prose prose-invert prose-slate max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-bold text-white flex items-center mb-4">
              <Eye className="w-5 h-5 mr-3 text-agri-green" /> 1. Introduction
            </h2>
            <p className="text-slate-300 leading-relaxed">
              At AgriBot, we are committed to protecting your privacy and ensuring the security of your agricultural data. This Privacy Policy explains how we collect, use, and safeguard your information when you use our AI-powered farming assistant.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white flex items-center mb-4">
              <FileText className="w-5 h-5 mr-3 text-agri-green" /> 2. Data Ownership
            </h2>
            <p className="text-slate-300 leading-relaxed">
              <strong>The Farmer Owns the Data.</strong> We believe that any data generated by your farming operations—including crop photos, yield projections, and soil diagnostics—remains your property. AgriBot acts as a processor and analytics provider, not an owner of your farm data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white flex items-center mb-4">
              <Lock className="w-5 h-5 mr-3 text-agri-green" /> 3. Information We Collect
            </h2>
            <ul className="list-disc pl-6 text-slate-300 space-y-2">
              <li><strong>Account Information:</strong> Name, email address, and farm location to personalize diagnostics.</li>
              <li><strong>Agricultural Data:</strong> Images of crops, plant health metadata, and historical scan data.</li>
              <li><strong>Usage Metrics:</strong> Log files, device information, and diagnostic results to improve our AI models.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white flex items-center mb-4">
              <Shield className="w-5 h-5 mr-3 text-agri-green" /> 4. AI Training Policy
            </h2>
            <p className="text-slate-300 leading-relaxed">
              We may use anonymized and aggregated agricultural data to improve the accuracy of our disease detection and crop diagnostic models. <strong>Personally identifiable information (PII) is never used for model training purposes</strong> without your explicit consent.
            </p>
          </section>

          <section className="bg-slate-800/30 p-6 rounded-2xl border border-slate-700/50">
            <h3 className="text-lg font-bold text-white mb-2">Data Portability</h3>
            <p className="text-slate-400 text-sm leading-relaxed">
              You have the right to export your scan history and diagnostic reports at any time. If you choose to delete your account, all your associated data will be permanently removed from our active servers within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">5. Contact Us</h2>
            <p className="text-slate-300 leading-relaxed">
              If you have any questions about this Privacy Policy or how we handle your data, please contact our data protection officer at:
              <br />
              <Link to="https://mail.google.com/mail/?view=cm&fs=1&to=iamhriturajsaha@gmail.com" target="_blank" className="text-agri-lightGreen hover:underline">iamhriturajsaha@gmail.com</Link>
            </p>
          </section>
        </div>
      </motion.div>
    </div>
  );
};

export default Privacy;
